### PR TITLE
Fetch Main Page on launch

### PR DESCRIPTION
**Pull request by kevinhinterlong**
Now uses the most up to date [main page](https://wiki.archlinux.org/index.php/Main_page) from the wiki

Addresses #11

### CODE REVIEW

**Comment by jtmcn** [comment]
The original startPage.html was a paired down version of the index.html. It intentionally removed some links that didn't work or make sense in the mobile app. For example, user login. Also links that went outside of the wiki. 

If we're going to add back everything, maybe it would be better to pull it directly from the server on application start. What do you think?

Also, have you seen the mobile version of the wiki? It didn't exist when this was created, but it might make sense to switch the source of the main page, and maybe all pages to it: https://wiki.archlinux.org/index.php?title=Main_page&mobileaction=toggle_view_mobile

**Comment by kevinhinterlong** [comment]
Yea it might make sense to just pull from the server when the app starts since there's no offline support as right now. This would fix #18 as well.

As for the new mobile wiki my guess (and preference) would be to keep it as it is. Maybe ask on [reddit](https://www.reddit.com/r/archlinux/) and see what they think?
If nothing else we could add it as a setting.

**Comment by kevinhinterlong** [comment]
Let me know if you have any thoughts on what to do for this

**Comment by kevinhinterlong** [comment]
I'm just going to keep the current theme for now. Now it's fetching the main page from the server on startup

**Pull request merged**
